services:
  webfoersterei_jsonparamconverter.dto_param_converter:
    class: Webfoersterei\Bundle\JsonParamConverterBundle\ParamConverter\JsonInputDtoParamConverter
    tags: [{ name: request.param_converter, converter: webfoersterei_jsonparamconverter }]
    arguments:
      - '@serializer'
      - '@validator'
